services:
  app-dev:
    image: logic-fabricator:latest
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./logs:/app/logs
    working_dir: /app
    tty: true
    profiles:
      - dev
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - .env.dev

  app-test:
    image: logic-fabricator:latest
    # command: poetry run pytest -m "not llm"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    working_dir: /app
    tty: true
    profiles:
      - test
    depends_on:
      neo4j-test:
        condition: service_healthy
    env_file:
      - .env.test

  neo4j:
    image: neo4j:5.22
    profiles:
      - dev
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"

    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_data:/data

  neo4j-test:
    image: neo4j:5.22
    profiles:
      - test
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_TEST_HTTP_PORT}:7474"
      - "${NEO4J_TEST_BOLT_PORT}:7687"

    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_test_data:/data

volumes:
  neo4j_data:
  neo4j_test_data:
