services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    working_dir: /app
    tty: true
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # For Neo4j connection
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

  neo4j:
    image: neo4j:5.22
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
