services:
  dev:
    image: logic-fabricator:latest
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    working_dir: /app
    tty: true
    profiles:
      - dev
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - .env
      - .env.dev

  test:
    image: logic-fabricator:latest
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    working_dir: /app
    tty: true
    profiles:
      - test
    depends_on:
      neo4j-test:
        condition: service_healthy
    env_file:
      - .env
      - .env.test
    command: poetry run pytest -m "not llm"

  neo4j:
    image: neo4j:5.22
    profiles:
      - dev
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_data:/data

  neo4j-test:
    image: neo4j:5.22
    profiles:
      - test
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_test_data:/data

volumes:
  neo4j_data:
  neo4j_test_data:
